apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: ebs-volume-snapshot
spec:
  snapshotClassName: csi-aws-snapclass
  source:
    name: ebs-claim
    kind: PersistentVolumeClaim
